DROP DATABASE IF EXISTS jojoapi_app;
CREATE DATABASE IF NOT EXISTS jojoapi_app;
USE jojoapi_app;
CREATE TABLE IF NOT EXISTS stands (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    `user` VARCHAR(255) NULL,
    description TEXT NOT NULL,
    origin_part INT NOT NULL,
    power VARCHAR(255) NOT NULL,
    speed VARCHAR(255) NOT NULL,
    `range` VARCHAR(255) NOT NULL,
    durability VARCHAR(255) NOT NULL,
    `precision` VARCHAR(255) NOT NULL,
    development_potential VARCHAR(255) NOT NULL,
    image VARCHAR(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NULL,
    provider VARCHAR(255) NULL DEFAULT 'local',
    provider_id VARCHAR(255) UNIQUE NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS submissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO stands (
        id,
        name,
        `user`,
        description,
        origin_part,
        power,
        speed,
        `range`,
        durability,
        `precision`,
        development_potential,
        image
    )
VALUES (
        1,
        'Star Platinum (Part 3)',
        'Jotaro Kujo',
        "Star Platinum (スタープラチナ（星の白金）, Sutā Purachina) is the Stand of Jotaro Kujo, primarily featured in the third part of the JoJo's Bizarre Adventure series, Stardust Crusaders. It also appears in the fourth part, Diamond is Unbreakable, and the sixth part, Stone Ocean. Star Platinum is a close-`range` Stand with exceptional strength and speed, as well as gaining the ability to stop time during the fight against DIO. Its overwhelming power, coupled with Jotaro's fighting prowess, make it one of the strongest and most iconic Stands in the series.",
        3,
        'A',
        'A',
        'C',
        'A',
        'A',
        'A',
        'https://static.jojowiki.com/images/thumb/2/2d/latest/20210316191453/Star_Platinum_SC_Infobox_Manga.png/1200px-Star_Platinum_SC_Infobox_Manga.png'
    ),
    (
        2,
        "Magician's Red",
        'Muhammad Avdol',
        "Magician's Red (マジシャンズ・レッド, Majishanzu Reddo) is the Stand of Muhammad Avdol, appearing in the third part of the JoJo's Bizarre Adventure series, Stardust Crusaders. It is a close-`range`, humanoid and bird-like Stand with the ability to control fire.",
        3,
        'B',
        'B',
        'C',
        'B',
        'C',
        'D',
        'https://static.wikia.nocookie.net/jojo/images/4/41/Magician%27s_Red.jpg/revision/latest?cb=20150718232814&path-prefix=es'
    ),
    (
        3,
        'Hermit Purple',
        'Joseph Joestar',
        "Hermit Purple (ハーミット・パープル, Hāmitto Pāpuru) is the Stand of Joseph Joestar, primarily featured in the third part of the JoJo's Bizarre Adventure series, Stardust Crusaders. It also appears in the fourth part, Diamond is Unbreakable. It manifests as a purple, vine-like stand that can extend very long distances, wrapping around and constricting objects or people or forming a shield. It can also be used to conduct Hamon energy and as a whip. It is not a very powerful stand in terms of attack, but it is very versatile and can be used in many different ways since it allows its user to control electronics and get spiritual photos or information from locations using electronic devices.",
        3,
        'D',
        'C',
        'D',
        'A',
        'D',
        'E',
        'https://static.jojowiki.com/images/thumb/c/c1/latest/20260226030336/Hermit_Purple_SC_Infobox_Manga.png/800px-Hermit_Purple_SC_Infobox_Manga.png'
    ),
    (
        4,
        'Hierophant Green',
        'Noriaki Kakyoin',
        "Hierophant Green (ハイエロファント・グリーン, Haierofanto Gurīn) is the long-`range`, artificial humanoid Stand of Noriaki Kakyoin. It is characterized by a melon-patterned green skin, light-colored armor, and a web-like, untwistable body capable of unraveling into tentacles to scout, possess, or attack from long distances using its main ability, Emerald Splash.",
        3,
        'C',
        'B',
        'A',
        'B',
        'C',
        'D',
        'https://static.jojowiki.com/images/thumb/8/8e/latest/20260314161255/Hierophant_Green_Infobox_Manga.png/600px-Hierophant_Green_Infobox_Manga.png'
    ),
    (
        5,
        'Silver Chariot',
        'Jean Pierre Polnareff',
        "Silver Chariot (シルバー・チャリオッツ, Shirubā Chariōtsu) is the Stand of Jean Pierre Polnareff, primarily featured in the third part of the JoJo's Bizarre Adventure series, Stardust Crusaders. It is a close-`range`, humanoid knight-like stand, clad in armor with the ability to control its rapier with incredible speed and `precision`. It can also remove its armor to become even faster, but at the cost of its defense.",
        3,
        'C',
        'A',
        'C',
        'B',
        'B',
        'C',
        'https://static.jojowiki.com/images/thumb/2/2f/latest/20221211192447/SilverChariotFirstAppearance.jpg/400px-SilverChariotFirstAppearance.jpg'
    ),
    (
        6,
        'The Fool',
        'Iggy',
        "The Fool (ザ・フール, Za Fūru) is the Stand of Iggy in JoJo's Bizarre Adventure: Stardust Crusaders, characterized as a highly versatile, powerful, and durable sand-based entity. Appearing as a mechanical dog with an Aztec-style mask, it manipulates sand to form weapons, glider wings, or clones, and its sand composition makes it nearly immune to conventional damage.",
        3,
        'B',
        'C',
        'D',
        'C',
        'D',
        'C',
        'https://static.jojowiki.com/images/thumb/f/f0/latest/20191015214051/The_Fool_Infobox_Manga.png/400px-The_Fool_Infobox_Manga.png'
    ),
    (
        7,
        'The World',
        'DIO',
        "The World (ザ・ワールド（世界）, Za Wārudo) is the Stand of the main antagonist of the third part, Stardust Crusaders, DIO. It is a close-`range`, muscular, humanoid stand similar to Star Platinum, with the ability to stop time for a limited amount of time. During this time, DIO can use his superhuman strength, vampiric abilities and speed to defeat his opponents.",
        3,
        'A',
        'A',
        'C',
        'A',
        'B',
        'B',
        'https://static.wikia.nocookie.net/jojo/images/9/92/DioBurandoDesune.png/revision/latest/scale-to-width-down/250?cb=20161116070759&path-prefix=es'
    ),
    (
        8,
        'Star Platinum (Part 4)',
        'Jotaro Kujo',
        "In JoJo's Bizarre Adventure: Diamond Is Unbreakable (Part 4), Star Platinum remains one of the strongest close-`range` Stands, featuring a refined, more purple-hued design and a 5 second time-stop ability reduced to roughly 0.5–2 seconds due to lack of use. It retains superhuman strength, speed, and `precision`, though Jotaro relies more on strategy.",
        4,
        'A',
        'A',
        'C',
        'A',
        'A',
        'A',
        'https://static.jojowiki.com/images/thumb/3/36/latest/20260311185811/Star_Platinum_DU_Infobox_Manga.png/600px-Star_Platinum_DU_Infobox_Manga.png'
    ),
    (
        9,
        'Crazy Diamond',
        'Josuke Higashikata',
        "Crazy Diamond (クレイジー・ダイヤモンド, Kureijī Daiyamondo) is the Stand of Josuke Higashikata, appearing in the fourth part of the JoJo's Bizarre Adventure series, Diamond is Unbreakable. It is a close-`range`, humanoid stand with the ability to repair any object or living being by touching it, excluding Josuke himself.",
        4,
        'A',
        'A',
        'D',
        'B',
        'B',
        'C',
        'https://static.wikia.nocookie.net/jjba/images/a/a5/CrazydiamondandJosuke.jpg/revision/latest/scale-to-width-down/250?cb=20150607220657'
    ),
    (
        10,
        'The Hand',
        'Okuyasu Nijimura',
        "The Hand (ザ・ハンド（手） Za Hando) is the Stand of Okuyasu Nijimura in JoJo's Bizarre Adventure: Diamond is Unbreakable, a close-`range` humanoid Stand with a blue and white robotic design and a unique power to erase matter and space with its right hand. Its key feature is its right palm, which can delete anything it swipes, effectively removing objects or space from existence without leaving a trace",
        4,
        'B',
        'B',
        'D',
        'C',
        'C',
        'C',
        'https://static.jojowiki.com/images/thumb/2/20/latest/20260218065303/The_Hand_Infobox_Manga.png/1200px-The_Hand_Infobox_Manga.png'
    ),
    (
        11,
        'Echoes (ACT 1)',
        'Koichi Hirose',
        "Echoes (エコーズ, Ekōzu) ACT 1 is the first evolution of Koichi Hirose's Stand in JoJo's Bizarre Adventure: Diamond is Unbreakable, appearing as a weak, long-`range`, alien-larva-like creature capable of manifesting sound as words on surfaces. It boasts a 50-meter `range` for scouting and manipulates targets by placing onomatopoeic sounds, such as \"ring\", on objects.",
        4,
        'E',
        'E',
        'B',
        'B',
        'C',
        'A',
        'https://static.wikia.nocookie.net/jojo/images/f/f7/Echoes.png/revision/latest?cb=20160623225315&path-prefix=es'
    ),
    (
        12,
        'Echoes (ACT 2)',
        'Koichi Hirose',
        "Echoes (エコーズ, Ekōzu) ACT 2 is the second evolution of Koichi Hirose's Stand in JoJo's Bizarre Adventure: Diamond is Unbreakable, it can manifest written sound effects (onomatopoeia) onto objects that activate as physical realities upon being touched. It represents a highly versatile evolution of Act 1, capable of causing various environmental effects, such as gnerating intense heat ('Sizzle'), immense wind pressure ('Woosh'), or creating a flexible, bouncy surface ('Boing')",
        4,
        'E',
        'E',
        'B',
        'B',
        'C',
        'A',
        'https://static.wikia.nocookie.net/jojo/images/5/55/Echoes_Act2_color.png/revision/latest/scale-to-width/360?cb=20161130211225&path-prefix=es'
    ),
    (
        13,
        'Echoes (ACT 3)',
        'Koichi Hirose',
        "Echoes (エコーズ, Ekōzu) ACT 3 is the third and Echoes Act 3 is the final, sentient form of Koichi Hirose’s Stand, specializing in close-`range` combat and gravity manipulation. Its primary ability, 3 Freeze, increases the weight of a targeted object or person within 5 meters, essentially paralyzing them by crushing them under intense gravity.",
        4,
        'C',
        'B',
        'C',
        'B',
        'C',
        'A',
        'https://static.wikia.nocookie.net/jjba/images/b/bc/Koichipic.jpg/revision/latest/scale-to-width-down/250?cb=20140818164251'
    ),
    (
        15,
        "Heaven's Door",
        'Rohan Kishibe',
        "Heaven's Door (天国への扉, Hebunzu Doā) is the Stand of Rohan Kishibe in JoJo's Bizarre Adventure: Diamond is Unbreakable, appearing as a small, humanoid figure resembling the character Pink Dark Boy from Rohan's manga, wearing a light-colored coat and a bowler hat. It transforms targets into living books, allowing Rohan to read their memories and write commands that override their free will, even defying physics.",
        4,
        'D',
        'B',
        'B',
        'B',
        'C',
        'A',
        'https://static.jojowiki.com/images/d/de/latest/20191228045732/Heaven%27s_Door_Infobox_Manga.png'
    ),
    (
        16,
        'Killer Queen',
        'Yoshikage Kira',
        "Killer Queen (キラークイーン, Kirā Kuīn), the Stand of Yoshikage Kira in JoJo's Bizarre Adventure: Diamond is Unbreakable, is a humanoid, cat-like stand focused on stealthy, untraceable murder, designed to eliminate evidence. It possesses three distinct bomb abilities—Primary Bomb (Bomb Transmutation), Sheer Heart Attack, and Bites the Dust—capable of atomizing targets completely.",
        4,
        'A',
        'B',
        'D',
        'B',
        'B',
        'A',
        'https://static.jojowiki.com/images/thumb/6/6c/latest/20210523204613/Vol38_cover_art.png/225px-Vol38_cover_art.png'
    ),
    (
        17,
        'Gold Experience',
        'Giorno Giovanna',
        "Gold Experience (ゴールド・エクスペリエンス, Gōrudo Ekusuperiensu) is Giorno Giovanna's versatile, close-`range` Stand in JoJo's Bizarre Adventure: Vento Aureo, featuring a humanoid design with ladybug motifs and a 2-meter `range`. It is renowned for creating, manipulating, and accelerating life, transforming inanimate objects into animals or plants.",
        5,
        'C',
        'A',
        'C',
        'D',
        'C',
        'A',
        'https://static.wikia.nocookie.net/jojo/images/1/10/Gold_Experience.jpg/revision/latest?cb=20150719215538&path-prefix=es'
    ),
    (
        18,
        'Sticky Fingers',
        'Bruno Bucciarati',
        "Sticky Fingers (スティッキィ・フィンガーズ, Sutikkī Fingāzu) is Bruno Bucciarati's Stand in JoJo's Bizarre Adventure: Vento Aureo, characterized by its zipper-like abilities. It allows Bruno to unzip anything—including air or himself—creating openings to slice through enemies, escape traps, or separate body parts without causing fatal damage, though the openings seal shut if not actively maintained.",
        5,
        'A',
        'A',
        'C',
        'D',
        'C',
        'D',
        'https://static.wikia.nocookie.net/jojo/images/9/91/Sticky_Fingers.png/revision/latest?cb=20160623172542&path-prefix=es'
    ),
    (
        19,
        'Aerosmith',
        'Narancia Ghirga',
        "Aerosmith (エアロ・スミス, Earo Sumisu) is Narancia Ghirga's Stand in JoJo's Bizarre Adventure: Vento Aureo, manifested as a miniature, American WWII-style fighter plane capable of autonomous flight and firing bullets. It operates at close to mid-`range`, possessing 50-meter `range`, and is equipped with a targeting system that detects carbon dioxide emissions.",
        5,
        'B',
        'B',
        'B',
        'C',
        'E',
        'C',
        'https://static.jojowiki.com/images/thumb/b/be/latest/20240220023709/Aerosmith_Infobox_Manga.jpg/800px-Aerosmith_Infobox_Manga.jpg'
    ),
    (
        20,
        'Sex Pistols',
        'Guido Mista',
        "Sex Pistols (セックス・ピストルズ, Sekkusu Pisutoruzu) is the Stand of Guido Mista in JoJo's Bizarre Adventure: Vento Aureo, consisting of six bullet-riding entities that manifest as miniature, humanoid figures. Each 'Pistol' possesses a number from 1 to 7 (excluding 4 due to a superstition), with abilities to alter the trajectory of Mista's bullets, allowing for precise, ricocheting shots.",
        5,
        'E',
        'C',
        'B',
        'A',
        'A',
        'B',
        'https://static.jojowiki.com/images/f/f5/latest/20191015213846/SexPistolsAv.png'
    ),
    (
        21,
        'Purple Haze',
        'Pannacotta Fugo',
        "Purple Haze (パープル・ヘイズ, Pāpuru Heizu), the Stand of Pannacotta Fugo, is a close-`range`, humanoid Stand in JoJo's Bizarre Adventure: Vento Aureo, characterized by its ferocity and its ability to dissolve organic matter with highly contagious purple bubbles. It wields 28 capsules of this corrosive virus, which activate upon being released from the Stand's head and spread rapidly within a 5-meter radius. The virus dissolves anything organic within 30 seconds, making it extremely dangerous to allies as well.",
        5,
        'A',
        'B',
        'C',
        'E',
        'E',
        'B',
        'https://static.wikia.nocookie.net/jojo/images/7/77/Purple_Haze.png/revision/latest/scale-to-width/360?cb=20161025210239&path-prefix=es'
    ),
    (
        22,
        'Moody Blues',
        'Leone Abbacchio',
        "Moody Blues (ムーディー・ブルース, Mūdī Burūsu) is Leone Abbacchio's Stand in JoJo's Bizarre Adventure: Vento Aureo, characterized by its humanoid shape and purple coloration, with a helmet-like headpiece and facial markings like a CD player. Its primary ability is 'Memory Play,' allowing it to physically manifest and replay past events in the location where they occurred, making it an invaluable tool for investigation.",
        5,
        'D',
        'B',
        'B',
        'C',
        'E',
        'D',
        'https://static.jojowiki.com/images/thumb/9/93/latest/20230520124240/Moody_Blues_Infobox_Manga.png/800px-Moody_Blues_Infobox_Manga.png'
    ),
    (
        23,
        'Golden Experience Requiem',
        'Giorno Giovanna',
        "Golden Experience Requiem (ゴールド・エクスペリエンス・レクイエム, Gōrudo Ekusuperiensu Rekuiemu) is Giorno Giovanna's ultimate Stand in JoJo's Bizarre Adventure: Vento Aureo after being pierced by the Requiem Arrow. It possesses the ability to revert any action or will against Giorno to zero, effectively trapping enemies in an infinite loop of death when killed by Golden Experience Requiem.",
        5,
        '∅',
        '∅',
        '∅',
        '∅',
        '∅',
        '∅',
        'https://static.wikia.nocookie.net/jojo/images/a/a7/GER_Profile.png/revision/latest?cb=20160716064528&path-prefix=es'
    ),
    (
        24,
        'King Crimson',
        'Diavolo',
        "King Crimson (キング・クリムゾン, Kingu Kurimuzon), the Stand of Diavolo, is the ultimate close-`range` humanoid Stand in JoJo's Bizarre Adventure: Vento Aureo, possessing the ability to erase time. King Crimson can manipulate time within a 10-second interval, allowing Diavolo to erase moments and skip through time while retaining the memories of the erased period and being able to reposition himself.",
        5,
        'A',
        'A',
        'E',
        'E',
        '?',
        '?',
        'https://i.pinimg.com/474x/58/68/d6/5868d65fad07b154a144d8a9e3cbbf24.jpg'
    ),
    (
        25,
        'Stone Free',
        'Jolyne Cujoh',
        "Stone Free (ストーン・フリー, Sutōn Furī) is Jolyne Cujoh's Stand in JoJo's Bizarre Adventure: Stone Ocean, known for its ability to transform Jolyne's body into string. Typically light blue/cyan, it wears green sunglasses, features sharp protrusions on its head, and is highly versatile, allowing for combat, traversal, and eavesdropping.",
        6,
        'A',
        'B',
        'C',
        'A',
        'C',
        'A',
        'https://static.wikia.nocookie.net/jojo/images/1/18/StoneFreeColor.png/revision/latest/scale-to-width-down/250?cb=20170904225928&path-prefix=es'
    ),
    (
        26,
        'Star Platinum (Part 6)',
        'Jotaro Kujo',
        "Star Platinum (スタープラチナ（星の白金） Sutā Purachina) in JoJo's Bizarre Adventure Part 6: Stone Ocean, remains one of the most powerful, close-`range`, and high-`precision` Stands, capable of stopping time for up to 5 seconds, the same as in Part 3. It retains immense strength and speed, though its appearance and color scheme are updated, featuring a mix of purple, blue, and gold with unique, flowing hair, its potential is realized.",
        6,
        'A',
        'A',
        'C',
        'A',
        'A',
        'Completed',
        'https://static.wikia.nocookie.net/jojo/images/1/1b/Star_p_1.png/revision/latest/scale-to-width/360?cb=20161229234538&path-prefix=es'
    ),
    (
        27,
        'Burning Down the House',
        'Emporio Alniño',
        "Burning Down the House (バーニング・ダウン・ザ・ハウス Bāningu Daun Za Hausu) is a unique, non-combat Stand that allows the user to see, interact with, and store 'ghost objects' and rooms that were destroyed in the past, being able to create a hidden base or refuge for the user and their allies.",
        6,
        '∅',
        '∅',
        '∅',
        '∅',
        '∅',
        '∅',
        'https://static.jojowiki.com/images/thumb/0/00/latest/20191015215502/BDtH_Infobox_Manga.png/640px-BDtH_Infobox_Manga.png'
    ),
    (
        28,
        'Weather Report',
        'Weather Report',
        "Weather Report (ウェザー・リポート, Wezā Ripōto) is the Stand of Weather Report in JoJo's Bizarre Adventure: Stone Ocean, characterized by its ability to control the weather within a certain `range`. It can create rain, wind, lightning, and even extreme weather conditions like hurricanes, tornadoes, frog rain and poisoning by pure oxygen making it a powerful force of nature.",
        6,
        'A',
        'B',
        'C',
        'A',
        'E',
        'A',
        'https://static.wikia.nocookie.net/jojo/images/4/42/WeatherRP.png/revision/latest?cb=20170124222802&path-prefix=es'
    ),
    (
        29,
        'Foo Fighters',
        'Foo Fighters',
        "Foo Fighters (フー・ファイターズ, Fū Faitāzu) is the Stand of Foo Fighters in JoJo's Bizarre Adventure: Stone Ocean, characterized by its ability to control and manipulate plankton. It can control a swarm of plankton to form a humanoid shape, allowing it to interact with the physical world. It can also disperse its body into a cloud of plankton, making it difficult to hit.",
        6,
        'B',
        'A',
        'C',
        'A',
        'C',
        'B',
        'https://static.jojowiki.com/images/0/07/latest/20210313143756/Foo_Fighters_Stand_Infobox_Manga.png'
    ),
    (
        30,
        'Diver Down',
        'Narciso Anasui',
        "Diver Down (ダイバー・ダウン, Daibā Daun) is Narciso Anasui's Stand in JoJo's Bizarre Adventure: Stone Ocean, characterized by its ability to enter and manipulate objects. It can phase through solid matter and alter its internal structure, allowing it to punch people from the inside out, reinforce objects to make them indestructible and enter their allies body to protect them for damage.",
        6,
        'A',
        'A',
        'E',
        'C',
        'B',
        'B',
        'https://i.pinimg.com/originals/60/b7/b0/60b7b0763a966e6eb54ee25bc2ba76ce.jpg'
    ),
    (
        31,
        'Kiss',
        'Ermes Costello',
        "Kiss (キス, Kisu) is a powerful, close-`range` humanoid Stand wielded by Ermes Costello in JoJo's Bizarre Adventure Part 6: Stone Ocean. Its primary ability is to duplicate any object or body part using lip-print stickers. When the sticker is removed, the original and the copy violently merge back together, inflicting heavy damage.",
        6,
        'A',
        'A',
        'A',
        'A',
        'C',
        'A',
        'https://static.jojowiki.com/images/thumb/7/77/latest/20210829145227/Kiss_Infobox_Manga.png/400px-Kiss_Infobox_Manga.png'
    ),
    (
        33,
        'Whitesnake',
        'Enrico Pucci',
        "Whitesnake (ホワイトスネイク, Howaito Sneiku) is the primary and first Stand of Enrico Pucci, the main antagonist of JoJo's Bizarre Adventure: Part 6 - Stone Ocean. It is a highly intelligent, humanoid Stand known for its menacing \"executioner\" design and ability to steal and manipulate both Stand abilities and human memories.",
        6,
        '?',
        'D',
        '?',
        'A',
        '?',
        '?',
        'https://static.wikia.nocookie.net/jojo/images/4/45/Whitesnake.png/revision/latest?cb=20170521061704&path-prefix=es'
    ),
    (
        34,
        'C-MOON',
        'Enrico Pucci',
        "C-Moon (C-MOONシー・ムーン, Shī Mūn) is a powerful, humanoid Stand belonging to Enrico Pucci, the primary antagonist in JoJo's Bizarre Adventure: Stone Ocean. Created by fusing Whitesnake with the Green Baby, it acts as a devastating transitional form with absolute control over gravity and spatial orientation.",
        6,
        '∅',
        'B',
        'B',
        '?',
        '?',
        '?',
        'https://static.wikia.nocookie.net/jojo/images/4/4a/C-Moon-0.png/revision/latest/scale-to-width-down/250?cb=20200718174612&path-prefix=es'
    ),
    (
        35,
        'Made in Heaven',
        'Enrico Pucci',
        "Made in Heaven (メイド・イン・ヘヴン, Meido In Hevun), originally known as Whitesnake (ホワイトスネイク, Howaito Sneiku) and later C-Moon (ディスク・アレイ, Disuku Arei) ) is the ultimate Stand of Enrico Pucci in JoJo's Bizarre Adventure: Stone Ocean. It is the culmination of DIO's plan to reach 'Heaven'. Its signature power accelerates universal time to unprecedented speeds, allowing it to rapidly reset the universe and dictate the destiny of all living beings by making them aware of their predestined fate.",
        6,
        'B',
        'Infinite',
        'C',
        'A',
        'C',
        'A',
        'https://static.jojowiki.com/images/b/bb/latest/20211117220434/Made_in_Heaven_Infobox_Manga.png'
    );